# Generated by Django 5.2.13 on 2026-04-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('food', 'Alimentos'), ('cleaning', 'Limpieza'), ('hygiene', 'Higiene'), ('home', 'Hogar')], max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('stock_min', models.IntegerField(default=1)),
                ('unit', models.CharField(default='unidad', max_length=20)),
                ('last_purchase', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
