# Generated by Django 5.2.13 on 2026-04-20 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_variableexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_payments', to='inventory.product')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
