# Generated by Django 5.2.13 on 2026-04-24 00:00

from django.db import migrations, models


def set_default_budget_buckets(apps, schema_editor):
    Product = apps.get_model("inventory", "Product")
    VariableExpense = apps.get_model("inventory", "VariableExpense")

    product_bucket_map = {
        "food": "needs",
        "cleaning": "needs",
        "hygiene": "needs",
        "home": "needs",
        "mobility": "needs",
        "maintenance": "needs",
        "subscription": "wants",
        "services": "needs",
        "assets": "needs",
        "leisure": "wants",
    }

    variable_bucket_map = {
        "mobility": "needs",
        "maintenance": "needs",
    }

    for product in Product.objects.all().only("id", "category"):
        product.budget_bucket = product_bucket_map.get(product.category, "needs")
        product.save(update_fields=["budget_bucket"])

    for expense in VariableExpense.objects.all().only("id", "category"):
        expense.budget_bucket = variable_bucket_map.get(expense.category, "needs")
        expense.save(update_fields=["budget_bucket"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_fixedexpensepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="budget_bucket",
            field=models.CharField(
                choices=[
                    ("needs", "Necesidades"),
                    ("wants", "Deseos"),
                    ("savings", "Ahorro / deuda"),
                ],
                default="needs",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="variableexpense",
            name="budget_bucket",
            field=models.CharField(
                choices=[
                    ("needs", "Necesidades"),
                    ("wants", "Deseos"),
                    ("savings", "Ahorro / deuda"),
                ],
                default="needs",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_default_budget_buckets, migrations.RunPython.noop),
    ]