# Generated by Django 5.2.13 on 2026-04-26 00:00

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


FIXED_EXPENSE_CATEGORIES = {"services", "subscription", "home"}


def migrate_fixed_expenses(apps, schema_editor):
    Product = apps.get_model("inventory", "Product")
    FixedExpense = apps.get_model("inventory", "FixedExpense")
    FixedExpensePayment = apps.get_model("inventory", "FixedExpensePayment")

    expense_by_product_id = {}

    for product in Product.objects.filter(category__in=FIXED_EXPENSE_CATEGORIES):
        expense = FixedExpense.objects.create(
            name=product.name,
            category=product.category,
            budget_bucket=product.budget_bucket,
            monthly_amount=Decimal(str(product.price or 0)),
            next_due_date=product.next_due_date,
            is_active=product.is_active,
            created_at=product.created_at,
            updated_at=product.updated_at,
        )
        expense_by_product_id[product.id] = expense.id

    for payment in FixedExpensePayment.objects.exclude(product_id=None):
        fixed_expense_id = expense_by_product_id.get(payment.product_id)
        if fixed_expense_id is None:
            continue
        payment.fixed_expense_id = fixed_expense_id
        payment.save(update_fields=["fixed_expense"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_budget_bucket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Alimentos"),
                    ("cleaning", "Limpieza"),
                    ("hygiene", "Higiene"),
                    ("assets", "Activos"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FixedExpense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("services", "Servicios"),
                            ("subscription", "Suscripciones"),
                            ("home", "Hogar"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "budget_bucket",
                    models.CharField(
                        choices=[
                            ("needs", "Necesidades"),
                            ("wants", "Deseos"),
                            ("savings", "Ahorro / deuda"),
                        ],
                        default="needs",
                        max_length=20,
                    ),
                ),
                ("monthly_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.AddField(
            model_name="fixedexpensepayment",
            name="fixed_expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_payments",
                to="inventory.fixedexpense",
            ),
        ),
        migrations.RunPython(migrate_fixed_expenses, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="fixedexpensepayment",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="fixedexpensepayment",
            name="product",
        ),
        migrations.AlterField(
            model_name="fixedexpensepayment",
            name="fixed_expense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="inventory.fixedexpense",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fixedexpensepayment",
            unique_together={("fixed_expense", "date")},
        ),
    ]
