# Generated by Django 5.2.13 on 2026-04-26 00:00

import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_split_fixed_expenses"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventorySettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config", models.JSONField(default=apps.inventory.models.clone_default_inventory_settings)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuracion de inventario",
                "verbose_name_plural": "Configuracion de inventario",
            },
        ),
        migrations.AlterField(
            model_name="fixedexpense",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(default="unidad", max_length=40),
        ),
        migrations.AlterField(
            model_name="variableexpense",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]