# Generated by Django 5.2.13 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("type", models.CharField(choices=[("consumable", "Consumible"), ("service", "Servicio"), ("subscription", "Suscripción"), ("asset", "Activo")], default="consumable", max_length=20)),
                ("budget_bucket", models.CharField(choices=[("needs", "Necesidades"), ("wants", "Deseos"), ("savings", "Ahorro / deuda")], default="needs", max_length=20)),
                ("stock", models.IntegerField(default=0)),
                ("stock_min", models.IntegerField(default=1)),
                ("unit", models.CharField(default="unidad", max_length=40)),
                ("price", models.FloatField(blank=True, null=True)),
                ("usage_frequency", models.CharField(choices=[("high", "Alta"), ("medium", "Media"), ("low", "Baja")], default="medium", max_length=10)),
                ("last_purchase", models.DateField(blank=True, null=True)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "inventory_product",
            },
        ),
    ]