# Generated by Django 5.2.13 on 2026-05-10 05:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_product_stock_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='purchases.product')),
            ],
            options={
                'db_table': 'inventory_productconsumption',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductRestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='purchases.product')),
            ],
            options={
                'db_table': 'inventory_productrestock',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
