# Generated by Django 5.2.13 on 2026-05-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('household', '0003_recurringtask_estimated_minutes'),
        ('purchases', '0002_alter_product_stock_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='integration_kind',
            field=models.CharField(blank=True, choices=[('', 'Sin integracion'), ('fixed_expense', 'Gasto fijo'), ('product_restock', 'Reposicion de producto'), ('product_expiry', 'Revision de vencimiento')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='linked_fixed_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_household_tasks', to='expenses.fixedexpense'),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_household_tasks', to='purchases.product'),
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='frequency_type',
            field=models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], max_length=20),
        ),
    ]
