# Generated by Django 5.2.13 on 2026-04-27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FixedExpense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("budget_bucket", models.CharField(choices=[("needs", "Necesidades"), ("wants", "Deseos"), ("savings", "Ahorro / deuda")], default="needs", max_length=20)),
                ("monthly_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "inventory_fixedexpense",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "inventory_income",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VariableExpense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("category", models.CharField(max_length=50)),
                ("budget_bucket", models.CharField(choices=[("needs", "Necesidades"), ("wants", "Deseos"), ("savings", "Ahorro / deuda")], default="needs", max_length=20)),
                ("description", models.CharField(blank=True, max_length=120)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "inventory_variableexpense",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FixedExpensePayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fixed_expense", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="payments", to="expenses.fixedexpense")),
            ],
            options={
                "db_table": "inventory_fixedexpensepayment",
                "ordering": ["-date", "-id"],
                "unique_together": {("fixed_expense", "date")},
            },
        ),
    ]