# Generated by Django 5.2.13 on 2026-04-27

from django.db import migrations, models

import apps.configuration.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventorySettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config", models.JSONField(default=apps.configuration.models.clone_default_inventory_settings)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "inventory_inventorysettings",
                "verbose_name": "Configuracion de inventario",
                "verbose_name_plural": "Configuracion de inventario",
            },
        ),
    ]