# Generated by Django 5.2.13 on 2026-04-27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entity_type", models.CharField(choices=[("income", "Ingreso"), ("variable_expense", "Gasto variable"), ("fixed_expense", "Gasto fijo"), ("fixed_expense_payment", "Pago fijo"), ("monthly_close", "Cierre mensual")], max_length=30)),
                ("action", models.CharField(choices=[("created", "Creado"), ("updated", "Actualizado"), ("deleted", "Eliminado"), ("payment_recorded", "Pago registrado"), ("monthly_closed", "Mes cerrado")], max_length=30)),
                ("entity_id", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=140)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("effective_date", models.DateField(default=django.utils.timezone.localdate)),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("previous_data", models.JSONField(blank=True, default=dict)),
                ("current_data", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "inventory_financialevent",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyClose",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("summary_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "inventory_monthlyclose",
                "ordering": ["-year", "-month", "-id"],
                "unique_together": {("month", "year")},
            },
        ),
    ]